### ISSUE TITLE
openhwcontrol does not start

### ISSUE THREAD

**Issue by evilphish** [kusti8/OpenHWControl#9]
Greetings, just trying out openhwcontrol to see whether it works with my Kraken X62 under Linux Mint 19.0. After installing the dependencies and openhwcontrol itself via pip3 I try to start openhwcontrol as root and am presented with the following error:

```
An unhandled exception has occurred
----------------------------------------
<class 'AttributeError'>: 
module 'hue_plus.hue' has no attribute 'profile_list'
----------------------------------------
  File "/usr/local/bin/openhwcontrol", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/openhwcontrol/ui.py", line 64, in main
    form = MainWindow()
  File "/usr/local/lib/python3.6/dist-packages/openhwcontrol/ui.py", line 162, in __init__
    self.profileListFunc()
  File "/usr/local/lib/python3.6/dist-packages/openhwcontrol/ui.py", line 1209, in profileListFunc
    if hue.profile_list():
```
Any remedy?

**Comment by djhorine** [comment]
Same issue here on Pop!_OS 18.10.

Another oddity, running hue profile list gives me a very similar error:
`Traceback (most recent call last):
  File "/usr/local/bin/hue", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/hue_plus/hue.py", line 152, in main
    profile_list()
NameError: name 'profile_list' is not defined
`

**Comment by sefatunckanat** [comment]
+1
![Screen Shot 2019-05-22 at 21 52 12](https://user-images.githubusercontent.com/9070463/58200516-9f12c400-7cdb-11e9-8465-c63d64a0a6c3.png)
